language: go

sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.8
    - RACKET_VERSION=HEAD

notifications:
  email:
    recipients:
      - mail@nurlan.co
    on_success: never
    on_failure: change

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git

install:
  - cat travis-racket/install-racket.sh | bash

before_script:
  - rm -rf travis-racket
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
  - find . -name "*.rkt" -exec racket {} \;
